// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2SfUQ8L9rHe8IdqpmGz6RQrlrduGngiY',
    appId: '1:652241787173:web:410f3f22848c31125e62cc',
    messagingSenderId: '652241787173',
    projectId: 'qari-4e344',
    authDomain: 'qari-4e344.firebaseapp.com',
    storageBucket: 'qari-4e344.firebasestorage.app',
    measurementId: 'G-W7PHZ3LHJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6gjOM97N5UXpmW7dVkVAgD1K6rdqgcGs',
    appId: '1:652241787173:android:6641ee92f48888895e62cc',
    messagingSenderId: '652241787173',
    projectId: 'qari-4e344',
    storageBucket: 'qari-4e344.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsrUnSHZOLHfQvsrkEFqvfUlJfmCkcxJY',
    appId: '1:652241787173:ios:24b657ab5bda9e235e62cc',
    messagingSenderId: '652241787173',
    projectId: 'qari-4e344',
    storageBucket: 'qari-4e344.firebasestorage.app',
    iosBundleId: 'com.example.qari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsrUnSHZOLHfQvsrkEFqvfUlJfmCkcxJY',
    appId: '1:652241787173:ios:24b657ab5bda9e235e62cc',
    messagingSenderId: '652241787173',
    projectId: 'qari-4e344',
    storageBucket: 'qari-4e344.firebasestorage.app',
    iosBundleId: 'com.example.qari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2SfUQ8L9rHe8IdqpmGz6RQrlrduGngiY',
    appId: '1:652241787173:web:9b0649068772648a5e62cc',
    messagingSenderId: '652241787173',
    projectId: 'qari-4e344',
    authDomain: 'qari-4e344.firebaseapp.com',
    storageBucket: 'qari-4e344.firebasestorage.app',
    measurementId: 'G-RHH4Z4F0JM',
  );
}
